schema = 3

[mod]
  [mod."cloud.google.com/go"]
    version = "v0.26.0"
    hash = "sha256-VZjIft7Xp7HLMgv4SNqZAOtkdCVVYeJmflKd3f2VLEw="
  [mod."github.com/BurntSushi/toml"]
    version = "v0.3.1"
    hash = "sha256-Rqak1dE/Aj/+Kx1/pl3Hifgt+Q3OzuZ5fJR+/x3nTbo="
  [mod."github.com/Masterminds/semver"]
    version = "v1.4.2"
    hash = "sha256-stN/mDrYj5FDBGnh63/99+r8fOgTlt7xxHtJ1MW8Tkw="
  [mod."github.com/Microsoft/go-winio"]
    version = "v0.4.11"
    hash = "sha256-dovTHQyjwKXW4wAynZrLw4yaEGzoiZ2A/2PdkX1+wZM="
  [mod."github.com/Shopify/logrus-bugsnag"]
    version = "v0.0.0-20171204204709-577dee27f20d"
    hash = "sha256-6ObnKCDPK06ajXEcngmQcoytSXjIqXW0rO/vcyZUftA="
  [mod."github.com/WatchBeam/clock"]
    version = "v0.0.0-20170901150240-b08e6b4da7ea"
    hash = "sha256-JF6AhRE47aFs5NFFWPKH2nZW8t8EFawrzkcmcaS1KaU="
  [mod."github.com/agl/ed25519"]
    version = "v0.0.0-20170116200512-5312a6153412"
    hash = "sha256-cQgEzXTv7Mg75LbEjW8uXO8+9VK7HC2MKOqNGtyEFe0="
  [mod."github.com/alecthomas/template"]
    version = "v0.0.0-20160405071501-a0175ee3bccc"
    hash = "sha256-sjuHfqM34m9uL7muq2JwZsj2HPRNuYSdZ2FuI+DeT2I="
  [mod."github.com/apache/thrift"]
    version = "v0.16.0"
    hash = "sha256-4jsjTxU5CZ6feurBx3pIY2JF5FsoMewVOQHeVtgHkdA="
  [mod."github.com/beorn7/perks"]
    version = "v0.0.0-20180321164747-3a771d992973"
    hash = "sha256-w0XZO3O1Hkptuq99wkc6GKzhPkJQByCCuUvJ4oi2VNA="
  [mod."github.com/bugsnag/bugsnag-go"]
    version = "v1.3.2"
    hash = "sha256-LT+bv/vAfVURx7sOF5FZwxUc60ynRNy0ycloOQDbb0E="
  [mod."github.com/bugsnag/panicwrap"]
    version = "v1.2.0"
    hash = "sha256-vcabgEaRet7Z0hDTV/eBzLVC15gpYwMfgiYs4tu1+rc="
  [mod."github.com/cenkalti/backoff"]
    version = "v2.0.0+incompatible"
    hash = "sha256-+cYi5iXtczSywA40KVYHsP0iXRcKRdpdnSbH62JKiEw="
  [mod."github.com/clbanning/mxj"]
    version = "v1.8.4"
    hash = "sha256-ZG1Z+YS6ZaKM8Ic9xvU9fe9LFwybhnBhQUKthvcPqhw="
  [mod."github.com/client9/misspell"]
    version = "v0.3.4"
    hash = "sha256-MIKnt4va/nPl+5cCgOvCyRGIORTnguieQhlj8ery4BU="
  [mod."github.com/cloudflare/cfssl"]
    version = "v0.0.0-20181102015659-ea4033a214e7"
    hash = "sha256-xyQcaRgeT1jCXkuFHLsFzl/lFhl/bO7+7SlYh8IfBqw="
  [mod."github.com/davecgh/go-spew"]
    version = "v1.1.1"
    hash = "sha256-nhzSUrE1fCkN0+RL04N4h8jWmRFPPPWbCuDc7Ss0akI="
  [mod."github.com/docker/distribution"]
    version = "v2.7.1+incompatible"
    hash = "sha256-8AFnEYjwqs8AzpSNBYgKmbUfFiCAxS+UH5SBFSuEctc="
  [mod."github.com/docker/go"]
    version = "v1.5.1-1"
    hash = "sha256-CpdMvIVpFj9/9FEGWOVelpyFj3qzYIjmw+XKuFZnvaw="
  [mod."github.com/docker/go-connections"]
    version = "v0.4.0"
    hash = "sha256-GHNIjOuuNp5lFQ308+nDNwQPGESCVV7bCUxSW5ZxZlc="
  [mod."github.com/docker/go-metrics"]
    version = "v0.0.0-20181218153428-b84716841b82"
    hash = "sha256-ADz/NDE7SEk1+1LHGfGfeXoYZdrHX8rcy9qvVJKBxbk="
  [mod."github.com/fsnotify/fsnotify"]
    version = "v1.4.7"
    hash = "sha256-j/Ts92oXa3k1MFU7Yd8/AqafRTsFn7V2pDKCyDJLah8="
  [mod."github.com/ghodss/yaml"]
    version = "v1.0.0"
    hash = "sha256-D+2i+EwF2YptR0m/OG4WIVVLL7tUC7XvgRQef2usfGo="
  [mod."github.com/go-bindata/go-bindata"]
    version = "v1.0.0"
    hash = "sha256-QRDgGllcB4Zb2jB9e1oezUPe+lXBZPz8GLsep7jzE94="
  [mod."github.com/go-ini/ini"]
    version = "v1.61.0"
    hash = "sha256-agfacsxEJlxwYxUEpUvHcodenzrnJaqyQi/KJ6OrV1E="
  [mod."github.com/go-kit/kit"]
    version = "v0.8.0"
    hash = "sha256-EWRJSQWDNhbzr9EvEzFg76Kn7G/2VBgsiAADHZvqU4s="
  [mod."github.com/go-logfmt/logfmt"]
    version = "v0.4.0"
    hash = "sha256-qX6aMMNTmN+D7LtQLZxW/LAKxRpze4vO77F2EQLrVRs="
  [mod."github.com/go-ole/go-ole"]
    version = "v1.2.6"
    hash = "sha256-+oxitLeJxYF19Z6g+6CgmCHJ1Y5D8raMi2Cb3M6nXCs="
  [mod."github.com/go-sql-driver/mysql"]
    version = "v1.4.1"
    hash = "sha256-2d2aKcq9juUUsHMxuZgC4Xl6t2WtluWuF4cW1a2Pbk8="
  [mod."github.com/go-stack/stack"]
    version = "v1.8.0"
    hash = "sha256-26RlTEcAkbewMUtmirKrDGQ1WJlNousp69v7HMopYnI="
  [mod."github.com/gogo/protobuf"]
    version = "v1.3.2"
    hash = "sha256-pogILFrrk+cAtb0ulqn9+gRZJ7sGnnLLdtqITvxvG6c="
  [mod."github.com/golang/glog"]
    version = "v0.0.0-20160126235308-23def4e6c14b"
    hash = "sha256-YDyL9TRikSXHSrYtITVA/ovYIYrdnZGym14XnslAYkk="
  [mod."github.com/golang/groupcache"]
    version = "v0.0.0-20190702054246-869f871628b6"
    hash = "sha256-fOnPnheIVato+xi3xc40UKw0vFLyd7IwKH2vJAKalmQ="
  [mod."github.com/golang/mock"]
    version = "v1.5.0"
    hash = "sha256-DwsajUB1hknylVqmvPyD+z5jjHiP4D+dNv9FUiuYYnU="
  [mod."github.com/golang/protobuf"]
    version = "v1.3.2"
    hash = "sha256-4fGAPuXMGpohqcqHeoIHwzCvkiWtIOAs0ewIhZ8JeU8="
  [mod."github.com/google/certificate-transparency-go"]
    version = "v1.0.21"
    hash = "sha256-kFkvwpvnFPXicdzGal1xNRxGd9Yq2N27SVCvPNO7DXY="
  [mod."github.com/google/fscrypt"]
    version = "v0.3.3"
    hash = "sha256-PWTMwi64h8V0SJcl6d3WtJ6ESwX0/C1A6sVBkBSyxsI="
  [mod."github.com/google/go-cmp"]
    version = "v0.3.1"
    hash = "sha256-oUPl5ojctSzSgOSdWB3HeQ5NOcTFtXly7HLSC2IiXLE="
  [mod."github.com/google/renameio"]
    version = "v0.1.0"
    hash = "sha256-XQ5yI+LMfFQuK7+T3Xx5jiaRP7GmiQSsPkFmm1TpIs4="
  [mod."github.com/google/uuid"]
    version = "v1.1.0"
    hash = "sha256-BjG7/ZzLdUODB4qkfH7c+tfilRaO4Vwz1A1q71ScpHs="
  [mod."github.com/gopherjs/gopherjs"]
    version = "v0.0.0-20181017120253-0766667cb4d1"
    hash = "sha256-AuXnjjoLbFZ85Oi8sldH117MBh+yCUB9HU5Y5syJ7Lg="
  [mod."github.com/gorilla/context"]
    version = "v1.1.1"
    hash = "sha256-pA7z/VCUIHuoP4wOeeJx+tLUFx7G8HQBjK6yfZCF5A4="
  [mod."github.com/gorilla/mux"]
    version = "v1.6.2"
    hash = "sha256-otFaMYQoJ6UHDdVJ2LLb5OAADYxVlG+v1r7TCYeof18="
  [mod."github.com/gorilla/websocket"]
    version = "v1.4.2"
    hash = "sha256-GhBLM/XTm2lFCyDvJbnCLAI2OyYXQV6W+jRPOQ1PdVY="
  [mod."github.com/groob/plist"]
    version = "v0.0.0-20190114192801-a99fbe489d03"
    hash = "sha256-HtoIZLdP0LMBpcvftuEwUOb3oFlhHAercBHPtqRGBnc="
  [mod."github.com/hailocab/go-hostpool"]
    version = "v0.0.0-20160125115350-e80d13ce29ed"
    hash = "sha256-3nb3OigyiSBjk+ixvP8HjQafsETODwLoW5PSOC4njRY="
  [mod."github.com/hashicorp/hcl"]
    version = "v1.0.0"
    hash = "sha256-xsRCmYyBfglMxeWUvTZqkaRLSW+V2FvNodEDjTGg1WA="
  [mod."github.com/hpcloud/tail"]
    version = "v1.0.0"
    hash = "sha256-7ByBr/RcOwIsGPCiCUpfNwUSvU18QAY+HMnCJr8uU1w="
  [mod."github.com/jessevdk/go-flags"]
    version = "v1.4.0"
    hash = "sha256-5tg5rdiLEbI53DAwp3Yps1y/6e9m9AcgzX3No4wE9dY="
  [mod."github.com/jinzhu/gorm"]
    version = "v1.9.1"
    hash = "sha256-VP/gmwWH+lmOTX0tFVki5OsoHefZUHybzE1Vg9ZNzH0="
  [mod."github.com/jinzhu/inflection"]
    version = "v0.0.0-20180308033659-04140366298a"
    hash = "sha256-EJs/8wMfLMQZRX2eOEHVfHoohneNdD59YeNKpbhlmOg="
  [mod."github.com/jmoiron/sqlx"]
    version = "v0.0.0-20180406164412-2aeb6a910c2b"
    hash = "sha256-S6uOsvV++34Xr56gJpObdEHUO2JIGOT7abWPc/uqKi0="
  [mod."github.com/jtolds/gls"]
    version = "v4.20.0+incompatible"
    hash = "sha256-Zu5naRjnwOYBzRv0CYhIZTizA0AajzOg7mJrL7Bo/cw="
  [mod."github.com/kardianos/osext"]
    version = "v0.0.0-20170510131534-ae77be60afb1"
    hash = "sha256-X66NFYdOW4hO8sSLcLcft/z2LrVzMLtQyEVKnPubzRQ="
  [mod."github.com/kisielk/errcheck"]
    version = "v1.5.0"
    hash = "sha256-ZmocFXtg+Thdup+RqDYC/Td3+m1nS0FydZecfsWXIzI="
  [mod."github.com/kisielk/gotool"]
    version = "v1.0.0"
    hash = "sha256-lsdQkue8gFz754PGqczUnvGiCQq87SruQtdrDdQVTpE="
  [mod."github.com/knightsc/system_policy"]
    version = "v1.1.1-0.20211029142728-5f4c0d5419cc"
    hash = "sha256-m/XNKreR1gRFJNjzPWP12zuxqXpJJkXTobH5KYMYxqU="
  [mod."github.com/kolide/kit"]
    version = "v0.0.0-20191023141830-6312ecc11c23"
    hash = "sha256-UxU0VjU1mI2zW8cAYq/RcvF7Z9d4mnpIqafxbS7p9h0="
  [mod."github.com/kolide/updater"]
    version = "v0.0.0-20190315001611-15bbc19b5b80"
    hash = "sha256-vv5hBrjoQ83IlRPBJK3FzGCyv7a0CyVSdg9r6MmqfBo="
  [mod."github.com/konsorten/go-windows-terminal-sequences"]
    version = "v1.0.2"
    hash = "sha256-p1sYnDuTd1y3pOq1KNPg2LqCWxhduH6Qj+yoGRMQtiY="
  [mod."github.com/kr/logfmt"]
    version = "v0.0.0-20140226030751-b84e30acd515"
    hash = "sha256-CePQbqWGtS8qP/Av9pkLiqZwH6RaZQff/s1l+1//jQo="
  [mod."github.com/kr/pretty"]
    version = "v0.1.0"
    hash = "sha256-Fx+TaNrxW0VfzonT2jnd5MU09RRz7GJZkqAtJR6/pKI="
  [mod."github.com/kr/pty"]
    version = "v1.1.2"
    hash = "sha256-qUwlTEYiYsM9ASuyMdzypnPIgjrFFxMqRK6dcsRYs2M="
  [mod."github.com/kr/text"]
    version = "v0.1.0"
    hash = "sha256-QT65kTrNypS5GPWGvgnCpGLPlVbQAL4IYvuqAKhepb4="
  [mod."github.com/lib/pq"]
    version = "v1.0.0"
    hash = "sha256-4kzHTc1ClrDiRX9UNW6jq3Hrbtg6bY7aQj63qyvrP4k="
  [mod."github.com/magiconair/properties"]
    version = "v1.8.0"
    hash = "sha256-tkt1yGEPbRjQvhsCkiD7jyLyhX2eo4AWx0ihzYUZIKg="
  [mod."github.com/mat/besticon"]
    version = "v3.9.0+incompatible"
    hash = "sha256-JU5noZvtdrn06HNinHssqhnIW1ZYV93c+lGI0h28+Lg="
  [mod."github.com/mattn/go-sqlite3"]
    version = "v1.10.0"
    hash = "sha256-vYcRbUDn6W+swRSCbcf6fWyg3bs6BAk7jK5HerUyv/4="
  [mod."github.com/matttproud/golang_protobuf_extensions"]
    version = "v1.0.1"
    hash = "sha256-ystDNStxR90j4CK+AMcEQ5oyYFRgWoGdvWlS0XQMDLQ="
  [mod."github.com/miekg/pkcs11"]
    version = "v0.0.0-20180208123018-5f6e0d0dad6f"
    hash = "sha256-8OoLMv7+BxzTXhLEVujLN232BAKLI0CDynNyapKj1zs="
  [mod."github.com/mitchellh/go-ps"]
    version = "v0.0.0-20170309133038-4fdf99ab2936"
    hash = "sha256-d0B5jThOqVDwVFVZrxQncUiG1QjMCHc4YMV+Q/H9GIY="
  [mod."github.com/mitchellh/mapstructure"]
    version = "v1.0.0"
    hash = "sha256-lYYNddW+9KKWHY2Vv6Yt9CqBI6D61s3AGQy8fx3BBjg="
  [mod."github.com/mixer/clock"]
    version = "v0.0.0-20170901150240-b08e6b4da7ea"
    hash = "sha256-JF6AhRE47aFs5NFFWPKH2nZW8t8EFawrzkcmcaS1KaU="
  [mod."github.com/nfnt/resize"]
    version = "v0.0.0-20180221191011-83c6a9932646"
    hash = "sha256-yvPV+HlDOyJsiwAcVHQkmtw8DHSXyw+cXHkigXm8rAA="
  [mod."github.com/oklog/run"]
    version = "v1.0.0"
    hash = "sha256-/LEK7Q4eG/hpydjQC2o7HgS9tc9ub3xdSVIpyoj6ct0="
  [mod."github.com/oklog/ulid"]
    version = "v0.3.0"
    hash = "sha256-XqRwXuKfcaMe24sIGrusHwA8PS2KKWywI7S3X/0Ftgs="
  [mod."github.com/onsi/ginkgo"]
    version = "v1.7.0"
    hash = "sha256-rjiQ3VODqmRAiAWdlZHQpx4LSRFeRD4iFuK/X5Qb/Ks="
  [mod."github.com/onsi/gomega"]
    version = "v1.4.3"
    hash = "sha256-O53umFMn7YHehD56BxaN38ofsvKB6IOr1eNDEcvDGbE="
  [mod."github.com/opencensus-integrations/ocsql"]
    version = "v0.1.1"
    hash = "sha256-grVfuiPFZP3KSMyZPAhoDl4aW5j2TRJIPsl0tEllCjo="
  [mod."github.com/opencontainers/go-digest"]
    version = "v1.0.0-rc1"
    hash = "sha256-CS7Cn14yxEg7hsLJVT7vCoXlR2dOXCJAEqQrZK877AU="
  [mod."github.com/opencontainers/image-spec"]
    version = "v1.0.2"
    hash = "sha256-X7kZoMYZNOIDpx8ziK7V+5YM07qiYWOE4yJo+sTOjjU="
  [mod."github.com/osquery/osquery-go"]
    version = "v0.0.0-20220317165851-954ac78f381f"
    hash = "sha256-h2kSJzbWMyYpga31b6cK7lypc7rE94HIEDUSEtw6XNI="
  [mod."github.com/pelletier/go-toml"]
    version = "v1.6.0"
    hash = "sha256-mVLY2MQ69LPAiPEKpzeao1LWWoSF7iFwQM7+a0N23Do="
  [mod."github.com/peterbourgon/ff/v3"]
    version = "v3.0.0"
    hash = "sha256-XQeuZIswjRetGWHQMAnQ6Ejud+Ix6NgQjrQ1WggkeQ0="
  [mod."github.com/pkg/errors"]
    version = "v0.8.1"
    hash = "sha256-oe3iddfoLRwpC3ki5fifHf2ZFprtg99iNak50shiuDw="
  [mod."github.com/pmezard/go-difflib"]
    version = "v1.0.0"
    hash = "sha256-/FtmHnaGjdvEIKAJtrUfEhV7EVo5A/eYrtdnUkuxLDA="
  [mod."github.com/prometheus/client_golang"]
    version = "v0.9.2"
    hash = "sha256-+kXLCOAYZS+C3WMEiDb/rJfKKI06jQjkqOApl83zZAk="
  [mod."github.com/prometheus/client_model"]
    version = "v0.0.0-20180712105110-5c3871d89910"
    hash = "sha256-YJ6Chzif7S1khu5AklB0pLsBNhJEe8204ky6RANy+hI="
  [mod."github.com/prometheus/common"]
    version = "v0.0.0-20181126121408-4724e9255275"
    hash = "sha256-xksei0cNo66dcYmNlmWY+OmckmUGnXmrtaX3bClEnV0="
  [mod."github.com/prometheus/procfs"]
    version = "v0.0.0-20181204211112-1dc9a6cbc91a"
    hash = "sha256-l9N+TMBe7LnMQ6ks777fPcnRbAFL6J+FSWXUmIR4z04="
  [mod."github.com/rogpeppe/go-internal"]
    version = "v1.3.0"
    hash = "sha256-JgiasZeXDy10syy7wmXtqRffDY7CJ1o5VNY+FmmAjVU="
  [mod."github.com/scjalliance/comshim"]
    version = "v0.0.0-20190308082608-cf06d2532c4e"
    hash = "sha256-HLhynogEXXxd6ckbfXl6JwHWCwl8vpBIJ/lRXV2IL9U="
  [mod."github.com/serenize/snaker"]
    version = "v0.0.0-20171204205717-a683aaf2d516"
    hash = "sha256-WB0iC0nR9t7ZLicsG9wxaatOlQH1ZfEI1q4bE/iOBoU="
  [mod."github.com/sirupsen/logrus"]
    version = "v1.4.0"
    hash = "sha256-HPT7WgU00xWyaamy2Q9XguI2EQkMZjG8Tvj8FB6TOPg="
  [mod."github.com/smartystreets/assertions"]
    version = "v0.0.0-20180927180507-b2de0cb4f26d"
    hash = "sha256-PoE+VQEnzJogI/mDBJ6dTCCR217nFjHfYWXQt9Vr9MQ="
  [mod."github.com/smartystreets/goconvey"]
    version = "v1.6.4"
    hash = "sha256-gDEvwEBgCVYi6daVRlQ2DUXFFlpybM1h4HyvvHphmM4="
  [mod."github.com/spf13/afero"]
    version = "v1.1.2"
    hash = "sha256-00yWOvw9GosWm6QkogM8MxpnVFRm/7BcdBLG4pQjO1Y="
  [mod."github.com/spf13/cast"]
    version = "v1.2.0"
    hash = "sha256-Imeibshp8sgdlPKooSSajjF1m1cA5XTTfksCgumZ65w="
  [mod."github.com/spf13/jwalterweatherman"]
    version = "v1.0.0"
    hash = "sha256-KLftz+gaA5wSkvLqvQ7CuboB79kKEoTJvgTtrXatbiQ="
  [mod."github.com/spf13/pflag"]
    version = "v1.0.2"
    hash = "sha256-yQ+vao6bzioxC2+euMtE17Z2UkWMtwbW6i/tNMnuADM="
  [mod."github.com/spf13/viper"]
    version = "v1.2.1"
    hash = "sha256-0/Snqnxkrqze1K1E8cHhWTXhNOm2+QKtghJ+FGf/7Hg="
  [mod."github.com/stretchr/objx"]
    version = "v0.1.1"
    hash = "sha256-HdGVZCuy7VprC5W9UxGbDmXqsKADMjpEDht7ilGVLco="
  [mod."github.com/stretchr/testify"]
    version = "v1.7.1"
    hash = "sha256-FcMk8eXO4sgVOYdpTZb8T+HpSXlZ0v4qd3UpP7DE6jk="
  [mod."github.com/theupdateframework/notary"]
    version = "v0.6.1"
    hash = "sha256-Rz9WDyilHW9/aSmrornc+GO9k8m+V8wHqZhTRoZKC9Y="
  [mod."github.com/urfave/cli"]
    version = "v1.20.0"
    hash = "sha256-l2ogVVY9/fmxFtjuaphK8myaPzVYDblPrLWm8kHkJn8="
  [mod."github.com/wadey/gocovmerge"]
    version = "v0.0.0-20160331181800-b5bfa59ec0ad"
    hash = "sha256-YbA4t26v6frdkh0uiXtmi8hiDYjR/FPBTxTwWlmfpwI="
  [mod."github.com/yuin/goldmark"]
    version = "v1.2.1"
    hash = "sha256-vrL87IsRgYTTHvCH2fodVu+ECk9UCu4kuCy3Ypy2Oos="
  [mod."go.etcd.io/bbolt"]
    version = "v1.3.6"
    hash = "sha256-DenVAmyN22xUiivk6fdJp4C9ZnUJXCMDUf8E0goRRV4="
  [mod."go.opencensus.io"]
    version = "v0.22.1"
    hash = "sha256-JJ2rPzmDWUE/VKfFWPEqFs0MMG5vZLiIRV6PqL+B3/0="
  [mod."golang.org/x/crypto"]
    version = "v0.0.0-20210220033148-5ea612d1eb83"
    hash = "sha256-ZacGMV1CFBAmShBQ/dN+C8Ls5ECHXXZdUiI1hcu4cFU="
  [mod."golang.org/x/exp"]
    version = "v0.0.0-20190121172915-509febef88a4"
    hash = "sha256-3aexxwjrNamNF7sKeDO0VhPMHbs+PPE4W1RisxYSHSo="
  [mod."golang.org/x/image"]
    version = "v0.0.0-20190227222117-0694c2d4d067"
    hash = "sha256-ZP6hLf3VHDGk80CjAhL6SMb/zq0jHC5/W0+deDvRmWw="
  [mod."golang.org/x/lint"]
    version = "v0.0.0-20190930215403-16217165b5de"
    hash = "sha256-8LRtePuV2+lVH+6aRVA4+yHalL1AWWKCq2z6DRivHEo="
  [mod."golang.org/x/mod"]
    version = "v0.3.0"
    hash = "sha256-c+KKzeDUDxrKIx8un1DpETlTK+DmHP+zUjRZrgs0ejo="
  [mod."golang.org/x/net"]
    version = "v0.0.0-20201021035429-f5854403a974"
    hash = "sha256-QzW8gkznloAcMLjxEF3xj8KllpK8VTnflkOuEeLvKDw="
  [mod."golang.org/x/oauth2"]
    version = "v0.0.0-20180821212333-d2e6202438be"
    hash = "sha256-x0Lvhts17qZLPpt43EuNzUXcKJ6krpGWLYiA0Fw5dnE="
  [mod."golang.org/x/sync"]
    version = "v0.0.0-20201020160332-67f06af15bc9"
    hash = "sha256-hfvviA1/duBMtleic86KvYNlUz3/V7XKVAggZtUldyQ="
  [mod."golang.org/x/sys"]
    version = "v0.0.0-20211025201205-69cdffdb9359"
    hash = "sha256-GE8ysfcBR4XoK0X9vmu6PVEQmnTCe5+GY9zUAF223L8="
  [mod."golang.org/x/term"]
    version = "v0.0.0-20210422114643-f5beecf764ed"
    hash = "sha256-Vnd025gp6+sXgz9Vn2KGRwFBhEigCMJ5Dbqiqekmgrw="
  [mod."golang.org/x/text"]
    version = "v0.3.3"
    hash = "sha256-kiauoT7vd7Mh2AW7TnceQyoCDsARxWkDZu1OSD9dCZw="
  [mod."golang.org/x/time"]
    version = "v0.0.0-20190308202827-9d24e82272b4"
    hash = "sha256-azbksMSLQf1CK0jF2i+ESjFenMDR88xRW1tov0metrg="
  [mod."golang.org/x/tools"]
    version = "v0.0.0-20210106214847-113979e3529a"
    hash = "sha256-VdoV0LIBWehslesNW1ETJ1WmO4KsGojC2HDdNAjGzsI="
  [mod."golang.org/x/xerrors"]
    version = "v0.0.0-20200804184101-5ec99f83aff1"
    hash = "sha256-62f++IO8Ia32CYy+xX8XDxCcT9r1sbPvVwoKV99gf7U="
  [mod."google.golang.org/appengine"]
    version = "v1.6.2"
    hash = "sha256-weEtAp7zBPkp+VuN4CFq2m6PwPzN7u/+1FA6Y4YGfOA="
  [mod."google.golang.org/genproto"]
    version = "v0.0.0-20190819201941-24fa4b261c55"
    hash = "sha256-Og+vLkTA3RffiJZoDneCazT9yJKlRTAjqUpMz8j3Kqg="
  [mod."google.golang.org/grpc"]
    version = "v1.23.0"
    hash = "sha256-VYuTCQ3EVTeOZgn2FQlQskzxmQsEcpNK67qCXSrJZM0="
  [mod."gopkg.in/check.v1"]
    version = "v1.0.0-20180628173108-788fd7840127"
    hash = "sha256-KsRJNTprd1UijnJusbHwQGM7Bdm45Jt/QL+cIUGNa2w="
  [mod."gopkg.in/dancannon/gorethink.v3"]
    version = "v3.0.5"
    hash = "sha256-elOqHe1xBdZ2KueGqzWeKY134xVHr8qFXVWN0rtLf9g="
  [mod."gopkg.in/errgo.v2"]
    version = "v2.1.0"
    hash = "sha256-Ir/MuxQFxvVJEciovGOZbM8ZfKJ/AYotPwYfH2FctRg="
  [mod."gopkg.in/fatih/pool.v2"]
    version = "v2.0.0"
    hash = "sha256-PeFMI2o6gCbp022IenBwqzjG7XNU8mW9aYdwVMDBujc="
  [mod."gopkg.in/fsnotify.v1"]
    version = "v1.4.7"
    hash = "sha256-j/Ts92oXa3k1MFU7Yd8/AqafRTsFn7V2pDKCyDJLah8="
  [mod."gopkg.in/gorethink/gorethink.v3"]
    version = "v3.0.5"
    hash = "sha256-elOqHe1xBdZ2KueGqzWeKY134xVHr8qFXVWN0rtLf9g="
  [mod."gopkg.in/ini.v1"]
    version = "v1.61.0"
    hash = "sha256-agfacsxEJlxwYxUEpUvHcodenzrnJaqyQi/KJ6OrV1E="
  [mod."gopkg.in/natefinch/lumberjack.v2"]
    version = "v2.0.0"
    hash = "sha256-CLir3wRkgNy7tXQWODk7u3RP/W7qIsO2LADdM6/vWtQ="
  [mod."gopkg.in/tomb.v1"]
    version = "v1.0.0-20141024135613-dd632973f1e7"
    hash = "sha256-W/4wBAvuaBFHhowB67SZZfXCRDp5tzbYG4vo81TAFdM="
  [mod."gopkg.in/yaml.v2"]
    version = "v2.2.4"
    hash = "sha256-4mnIZoZTmJhCe8pX+ChsXTSxN1rYPWpZbhNFfsqRfIU="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.0-20210107192922-496545a6307b"
    hash = "sha256-j8yDji+vqsitpRZirpb4w/Em8nstgf28wpwkcrOlxBk="
  [mod."honnef.co/go/tools"]
    version = "v0.0.1-2019.2.3"
    hash = "sha256-jpCzv1UG8xGB44IA+kcAXDULYQlJWqa816GYP+BQoMs="
  [mod."howett.net/plist"]
    version = "v0.0.0-20181124034731-591f970eefbb"
    hash = "sha256-aXZYdLMlttOdcvg3D2mjiTA2VleO9WqcV2+halwmJ78="
  [mod."software.sslmate.com/src/go-pkcs12"]
    version = "v0.0.0-20210415151418-c5206de65a78"
    hash = "sha256-x+163RJQPv3pczkTj9LKQhobEm6e6+uohQi4fXz65SQ="
